### ISSUE TITLE
Ordered lists starting with 0

### ISSUE THREAD

**Issue by colinodell** [jgm/commonmark.js#10]
[According to the spec](http://spec.commonmark.org/0.17/#ordered-list-marker):

> An ordered list marker is a sequence of one of more digits (`0-9`), followed by either a `.` character or a `)` character.

`0.` seems to be recognized as an ordered list marker, but the resulting `start` attribute does not get set to `0` as expected: http://spec.commonmark.org/dingus/?text=0.%20Zero%0A1.%20One

(This issue may also affect cmark - I have not tested that)

**Comment by jgm** [comment]
Thanks, should be fixed now. cmark not affected.
