### ISSUE TITLE
CommonMark does not support space in link address anymore

### ISSUE THREAD

**Issue by duongphuhiep** [jgm/commonmark.js#100]
Hi,

CommonMark doesn't parse the following node as Link (though it worked in previous version)
```
[some text](#post/contain spaces in address)
```

In order to make it work, I must to force users to type as following:
```
[some text](#post/contain%20spaces%20in%20address)
```

What is the best way to get back the old behaviour?

Thank you

**Comment by jgm** [comment]
This conforms to the spec.
See http://spec.commonmark.org/0.25/#link-destination

+++ DUONG Phu-Hiep [May 21 16 16:17 ]:
