### ISSUE TITLE
HTML inside of blockquotes

### ISSUE THREAD

**Issue by colinodell** [jgm/commonmark.js#103]
According to [section 4.6 the spec](http://spec.commonmark.org/0.25/#html-blocks):

> [An HTML block] ends with the first subsequent line that meets a matching end condition, or the last line of the **document**, if no line is encountered that meets the end condition.

If we convert the following input with the reference parser ([see dingus](http://spec.commonmark.org/dingus/?text=%3E%20and%20the%20test%3A%0A%3E%0A%3E%20%3C%3Fphp%0A%3E%20ini_set(%22pcntl.async_signals%22%2C%20%221%22)%3B%0A%0AWe%20use%202%2F3%20vote%20for%20%22a%20feature%20affecting%20the%20language%20itself%22.)):

```md
> and the test:
>
> <?php
> ini_set("pcntl.async_signals", "1");

We use 2/3 vote for "a feature affecting the language itself".
```

We end up with the following HTML:

```html
<blockquote>
<p>and the test:</p>
<?php
ini_set("pcntl.async_signals", "1");
</blockquote>
<p>We use 2/3 vote for &quot;a feature affecting the language itself&quot;.</p>
```

And this is the AST:

```xml
<document xmlns="http://commonmark.org/xml/1.0">
  <block_quote>
    <paragraph>
      <text>and the test:</text>
    </paragraph>
    <html_block>&lt;?php
ini_set(&quot;pcntl.async_signals&quot;, &quot;1&quot;);</html_block>
  </block_quote>
  <paragraph>
    ...
  </paragraph>
</document>
```

(Unimportant bits removed for brevity)

However, if I'm reading the spec correctly, shouldn't the final line of the input (`We use 2/3 vote...`) be included in the HTML block since no end condition was matched in the **document**?  Instead it seems to be ending because no end condition was matched in the **blockquote** container.

Alternatively, perhaps the spec needs to be revised in one of two ways:

1. State that HTML leaf blocks end on "the last line of the **container**" instead of "the last line of the **document**".  This would match the current behavior, if that's desired.
2. Disallow parsing of HTML leaf blocks within blockquotes.

Alternative 2 seems to be the most common implementation [according to Babelmark 2](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+and+the+test%3A%0A%3E%0A%3E+%3C%3Fphp%0A%3E+ini_set(%22pcntl.async_signals%22%2C+%221%22)%3B%0A%0AWe+use+2%2F3+vote+for+%22a+feature+affecting+the+language+itself%22.%0A) and matches what I'd expect as an end-user.  I'd therefore lean towards that as the ideal solution.

Related issue from my PHP fork of this reference parser: https://github.com/thephpleague/commonmark/issues/252

**Comment by jgm** [comment]
+++ colinodell [Jun 27 16 14:24 ]:
>   According to [1]section 4.6 the spec:
>
>     [An HTML block] ends with the first subsequent line that meets a
>     matching end condition, or the last line of the document, if no line
>     is encountered that meets the end condition.
>
>   However, if I'm reading the spec correctly, shouldn't the final line of
>   the input (We use 2/3 vote...) be included in the HTML block since no
>   end condition was matched in the document? Instead it seems to be
>   ending because no end condition was matched in the blockquote
>   container.

You're right.  It shouldn't say "the end of the document."
Rather, it should say something like "the end of the
document or other containing block" (which may be
a blockquote or list item).

>   Alternatively, perhaps the spec needs to be revised in one of two ways:
>    1. State that HTML leaf blocks end on "the last line of the container"
>       instead of "the last line of the document". This would match the
>       current behavior, if that's desired.

Yes, that's what it should say.

>    2. Disallow parsing of HTML leaf blocks within blockquotes.
>
>   Alternative 2 seems to be the most common implementation [3]according
>   to Babelmark 2 and matches what I'd expect as an end-user. I'd
>   therefore lean towards that as the ideal solution.

No, all implementations allow HTML inside blockquotes:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+%3Cdiv%3E%0A%3E+hi%0A%3E+%3C%2Fdiv%3E%0A

What you're seeing is variable support for this particular
case (`<?php` with an unclosed tag).

**Comment by colinodell** [comment]
> Rather, it should say something like "the end of the document or other containing block" (which may be a blockquote or list item).

Thanks, I've created a pull request for this change: https://github.com/jgm/CommonMark/pull/412

> What you're seeing is variable support for this particular case (`<?php` with an unclosed tag).

You're right, good catch!  I've started a new thread to discuss this particular case here: https://talk.commonmark.org/t/type-3-html-blocks/2135

I'm going to mark this issue as closed since you've confirmed that this behavior is not a bug with the JS parser.
