### ISSUE TITLE
What's the difference between lib/html.js and lib/render/html.js?

### ISSUE THREAD

**Issue by iamwilhelm** [jgm/commonmark.js#113]
The former, `lib/html.js` doesn't seem to be used. If I want to write my own renderer, which one should I look at as an example? I assume `lib/render/html.js`

**Comment by jgm** [comment]
Yes, we haven't quite completed the transition to the
abstract renderers, but yes, lib/render/html.js is the
one to use.

+++ Wil Chung [Dec 02 16 10:18 ]:
