### ISSUE TITLE
"&" and spacing

### ISSUE THREAD

**Issue by stevenvachon** [jgm/commonmark.js#117]
```js
(new (require("commonmark").Parser)).parse("### a & b")
```
…produces nodes with `_literal` values of `'a '` and `' b'`. I think this is fine.

The next part is where I'm missing information. When [npmjs.com](https://npmjs.com) and [github.com](https://github.com) convert this header into a hash/fragment link, it becomes `#a--b`. I think this is ugly. Where does this transformation take place?

**Comment by jgm** [comment]
+++ Steven Vachon [Apr 28 17 14:43 ]:
>(new (require("commonmark").Parser)).parse("### a & b")
>
>   …produces nodes with 'a ' and ' b' values. I think this is fine.
>
>   The next part is where I'm missing information. When npmjs.com and
>   github.com turn these headers into hash/fragment link, they end up
>   being #a--b. Where does this transformation take place?

I don't know, but it has nothing to do with this library.

**Comment by stevenvachon** [comment]
Well, I know that github.com is using this library, and am guessing that npmjs.com is too because the pages render the same.

**Comment by jgm** [comment]
GitHub uses a their own fork of jgm/cmark, the C
reference implementation. This is the JavaScript reference
implementation.

+++ Steven Vachon [Apr 29 17 08:17 ]:

**Comment by stevenvachon** [comment]
Yeah, just discovered that after reading your previous response. Thank you.
