### ISSUE TITLE
Punctuation set is different from the spec

### ISSUE THREAD

**Issue by rlidwka** [jgm/commonmark.js#121]
[CommonMark/spec.txt](https://github.com/jgm/CommonMark/blob/c94efe8d3adbfbe6418c7ea59ab3802472c7e4b2/spec.txt#L329-L332) defines this punctuation set:

```
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```

Regexp in [commonmark.js/lib/inlines.js](https://github.com/jgm/commonmark.js/blob/277b0d71e7494d5e38666c00c281372ae9799b59/lib/inlines.js#L39) uses smaller character set:

```
!"#%&'()*,-./:;?@[\]_{}
```

As a result, `^_test_` is not rendered as emphasis, even though according to spec it should (and cmark renders it as an emphasis).

```
$ echo '^_test_' | ./cmark/build/src/cmark 
<p>^<em>test</em></p>
$ echo '^_test_' | ./commonmark.js/bin/commonmark 
<p>^_test_</p>
```

Original issue: https://github.com/markdown-it/markdown-it/issues/380

**Comment by SamSaffron** [comment]
Note, fixing this will cause: 

```
https://derp.com?_test_=1
```

To render as: 

```
<p>https://derp.com?<em>test</em>=1</p>
```

It is 100% correct to fix the implementation so it correctly implements the spec, but the spec does do some weird things with legit URLs in the wild.
