### ISSUE TITLE
Typo in blocks.js?

### ISSUE THREAD

**Issue by dpeek** [jgm/commonmark.js#13]
While porting this to a typed language (Haxe) I noticed a potential typo in `lib/blocks.js`:
https://github.com/jgm/commonmark.js/blob/master/lib/blocks.js#L686

I'm thinking `above` should just be `block._parent` as we want to exit here when tip is `null`:
https://github.com/jgm/commonmark.js/blob/master/lib/blocks.js#L737

Or maybe not... I'm new here ;)

**Comment by jgm** [comment]
Thanks - you're right, this is a mistake.  `this.top` isn't even set anywhere, and that's the only reason this didn't go into an infinite loop.  This is a remnant of earlier archictecture.
