### ISSUE TITLE
Test #8 from smart_punct.txt

### ISSUE THREAD

**Issue by dikmax** [jgm/commonmark.js#14]
It looks like test #8 from smart_punct.txt fail, at least in dingus.

    "A paragraph with no closing quote.

    "Second paragraph by same speaker, in fiction."

Dingus shows first paragraph with closing quote, while there should be open quote.

**Comment by jgm** [comment]
Closed by db02aff1da5cfd1e614470b850c49601b5a03812
which added the tests.
