### ISSUE TITLE
ETA until stability?

### ISSUE THREAD

**Issue by ChiperSoft** [jgm/commonmark.js#15]
I'm considering switching [dox](https://github.com/tj/dox) over to using commonmark, but I got bit by the massive API and AST changes between 0.12 and 0.17 and am hesitant to make it a dependency while things are changing so much.

Do you have an idea of when the package might be stable for a 1.0 release?

**Comment by jgm** [comment]
Sorry about that.  I'm thinking some time this summer, after we
have a 1.0 for the spec itself.  The JavaScript API isn't yet what I'd
like it to be -- I'm sort in the middle of changes that will make it
easier to modify the parser and renderer.  But I haven't had a lot of
time to work on it lately.

+++ Jarvis Badgley [Mar 18 15 10:52 ]:

**Comment by matmuchrapna** [comment]
@jgm can you point me to issue about 1.0 release for the spec?

**Comment by jgm** [comment]
@matmuchrapna - I'm not sure what you mean.  I will be posting a "roadmap" for 1.0 before too long; I just haven't had time to do it yet.
