### ISSUE TITLE
Add source positions for inline elements

### ISSUE THREAD

**Issue by jgm** [jgm/commonmark.js#28]
This would make it possible to use commonmark.js for syntax highlighting.

**Comment by iamstarkov** [comment]
Are you sure that markdown transform engine should handle highlighting?

**Comment by jgm** [comment]
@iamstarkov - why not?  We have access to source position information when we're parsing, so why not include it in the AST?  There are other things it might be useful for, in addition to syntax highlighting.  Also:  syntax highlighting for Markdown is really hard to get right without a full parser.  In programming languages, a pretty simple tokenizer will usually suffice.  But in Markdown you can't tell whether a `*` character is, for example, a literal `*` character, the start of emphasis, the end of emphasis, part of the start of strong emphasis, or part of the end of strong emphasis, until you actually parse the text.

**Comment by iamstarkov** [comment]
I think commonmark should not handle highlighting in any way mainly to keep it simple and because npm have already tons of highlighting packages. In this situation, commonmark’s consumer will be free to choose any highlighting module he want. Summary: commonmark will be simple, highlightning issues will be created outside this repo, you as maintainer will have much more free time, commonmark’s consumers will be happy to have a choice.

That’s why I argue contra. From my point of view, commonmark should be able only to transform code blocks from `md→html`, optionally exposing classes defined with backticks (in this case, it will be `javascript`):

    ```javascript
    // some code
    ```

**Comment by jgm** [comment]
+++ Vladimir Starkov [Apr 23 15 09:27 ]:
>   I think commonmark should not handle highlighting in any way mainly to
>   keep it simple and because npm have already tons of highlighting
>   packages. In this situation, commonmark’s consumer will be free to
>   choose any highlighting module he want. Summary: commonmark will be
>   simple, highlightning issues will be created outside this repo, you as
>   maintainer will have much more free time, commonmark’s consumers will
>   be happy to have a choice.

I think the issue is that existing syntax highlighting libraries are very error-prone in highlighting Markdown/CommonMark specifically.

>   That’s why I argue contra. From my point of view, commonmark should be
>   able only to transform code blocks from md→html, optionally exposing
>   classes defined with backticks (in this case, it will be javascript):

You may be misunderstanding the intent of this.  The proposal is not to add syntax highlighting of code blocks to commonmark.js.  I agree that it's better to leave this to the user of the library.  The proposal is just to add some source position information, which would allow someone to use commonmark.js in writing a syntax highlighter for CommonMark syntax itself.

**Comment by iamstarkov** [comment]
Maybe I get you point.

Can I ask you to show samples of how this will work in the end? workflow sketch or spec. I want to clear understand idea of issue.

**Comment by jgm** [comment]
Okay, I've thought about this some more, and I'm no longer sure that source positions for inline elements (at least in the form of start and end positions) would be so useful.  Consider:

```
1.  > This is a *block
    > quote* inside a list item.
```

Knowing where the emphasized text starts and ends doesn't really tell you enough about which parts of the source it corresponds to (and hence, e.g., which parts to highlight as emphasized).

(This is a belated recognition of @zdne's comment in jgm/CommonMark#57.)

I'm now coming around to the view that what we need is source maps, not start and end positions for each element.  So I'll close this and open a new issue for that.
