### ISSUE TITLE
sourcepos not correct

### ISSUE THREAD

**Issue by zjuasmn** [jgm/commonmark.js#3]
sourcepos attribute in AST is not correct when parser run for more than 1 time:

```javascript
     var reader = new commonmark.Parser();
     var writer = new commonmark.HtmlRenderer({sourcepos:true});
     console.log(writer.render(reader.parse("Hello *world*")));
     console.log(writer.render(reader.parse("Hello *world*")));
```
Now the result is 
```
    <p data-sourcepos="1:1-1:13">Hello <em>world</em></p>
    <p data-sourcepos="2:1-1:13">Hello <em>world</em></p>
```
And I wonder why should the sourcepos be 1-based instead of 0-based?

**Comment by jgm** [comment]
Thanks for the report. I believe this is now fixed.

>   BTW, should the sourcepos be 1-based instead of 0-based?

The current code thinks of the left-most column as 1 and the
first line as 1.  This is fairly intuitive, I think.  My
text editor counts lines and columns the same way.  I'd
consider an argument for another approach, though.
