### ISSUE TITLE
tests for AST tree

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#35]
Do you remember my topic about [commonmark API design][api]?

I’m in process of figuring out how to do it in the best way. To proof the concept, I chose to create helper module. One of the method is `ast()`, but I have no idea how to test it properly and didn‘t find any tests related to AST tree in commonmark.js too =(.

Firstly, I thought about `deepEqual`, but it failed due to circular deps, then I tried simple `equal` with `JSON.stringify()` but circular deps broke everything here too.

How can I verify that AST tree have proper structure? any advice or tip will be useful, thanks

[api]: http://talk.commonmark.org/t/api-design-can-be-better/1169

**Comment by iamstarkov** [comment]
any advice?

**Comment by iamstarkov** [comment]
polite ping

**Comment by iamstarkov** [comment]
=((

**Comment by iamstarkov** [comment]
why it’s closed without any message?

**Comment by jgm** [comment]
This tracker is for bug reports, not questions.
I have limited time to reply to programming questions.
CommonMark.dtd in jgm/CommonMark can serve as a reference for the proper structure of the AST, but figuring out how to check this is up to you.
