### ISSUE TITLE
header vs heading

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#36]
Why `H1-6` titles have `header` type instead of more [w3c compliant](http://www.w3.org/TR/html-markup/h1.html) `heading`?

PS. Sorry for asking too many questions, is it okay?

**Comment by jgm** [comment]
+++ Vladimir Starkov [May 09 15 22:36 ]:
>   Why H1-6 titles have header type instead of more [1]w3c compliant
>   heading?

I assume you're just talking about the name?

I think the reason is that John Gruber called them "headers" in the original Markdown syntax description. (And presumably this goes back to prior art like setext and atx.)

**Comment by iamstarkov** [comment]
yep, thanks
