### ISSUE TITLE
Inconsistent handling of malformed link reference titles

### ISSUE THREAD

**Issue by BigBadaboom** [jgm/commonmark.js#39]
Consider these two samples. Both have malformed link titles.

```
[foo]: /url
"title

[foo]
```
http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%3A%20%2Furl%0A%22title%0A%0A%5Bfoo%5D

and

```
[foo]: /url
"title" ok

[foo]
```
http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%3A%20%2Furl%0A%22title%22%20ok%0A%0A%5Bfoo%5D

The first sample creates a link reference, but the second one doesn't.  I believe they should both be treated the same - ie. links in both cases.

**Comment by jgm** [comment]
Fixed by #49.
