### ISSUE TITLE
Dingus shows incorrect sourcepos value for paragraphs

### ISSUE THREAD

**Issue by Knagis** [jgm/commonmark.js#4]
<http://spec.commonmark.org/dingus.html?text=123>

At first the value seems correct (`<paragraph data-sourcepos="1:1-1:3">`) but as soon as you start typing/clicking in the editor, it goes off: `<paragraph data-sourcepos="19:1-1:12">`

Probably because `this.lineNumber` is not reset.

**Comment by jgm** [comment]
I think this is a dup of #3.  I'll update the live dingus.

**Comment by jgm** [comment]
Try it now, I've updated the code on the dingus.

**Comment by Knagis** [comment]
Yes, this has been fixed.
