### ISSUE TITLE
Dingus doesn't display list markers if first block in item is Code Block

### ISSUE THREAD

**Issue by BigBadaboom** [jgm/commonmark.js#40]
If you try the following bit of markdown in the dingus:

```
-     new list with indented code block
```

[Show in dingus](http://spec.commonmark.org/dingus/?text=-%20%20%20%20%20new%20list%20with%20indented%20code%20block%0A)

the bullet will not be displayed.

This seems to be due to a clash with the Bootstrap CSS definition for ```pre```.  Bootstrap is doing a 

```
pre {
  overflow: auto;
}
```

which is causing the list markers to be invisible.  If you add ```overflow: visible``` to the definition for ```pre``` in dingus.css it is visible again.

```
pre {
  display: block;
  padding: 0.5em;
  color: #333;
  background: #f8f8ff;
  overflow: visible;
}
```

**Comment by vyp** [comment]
Which browser/browser engine are you using? I see http://i.imgur.com/J7KgjPz.png. Otoh, adding `overflow: visible` does not change anything either (to what I see), except it's my understanding that `auto` will automatically put scroll bars if the content is too long, whereas `visible` will just show it (expanding outside boundaries if necessary). Ultimately it's whatever @jgm prefers.

**Comment by BigBadaboom** [comment]
Sorry. Should have said.  I'm using Chrome.  Tested in v42 and v43.

![capture](https://cloud.githubusercontent.com/assets/840288/7786820/9b789566-0239-11e5-99a9-fb40d6daf88a.PNG)

The `overflow:visible` was just a workaround I found.  It may not be the best fix.

**Comment by vyp** [comment]
@BigBadaboom Thanks.

**Comment by BigBadaboom** [comment]
Okay. Turns out it is a webkit bug that is eight years old. :/

https://code.google.com/p/chromium/issues/detail?id=344941

**Comment by vyp** [comment]
Wow, good find. I wonder why it's been unresolved for so long, seems like a pretty major bug (at least for webkit/blink).
