### ISSUE TITLE
Allow Node classes to be set

### ISSUE THREAD

**Issue by bebraw** [jgm/commonmark.js#41]
I have to transform some custom syntax like this to HTML:

```
# Demo

T> This is some tip.

W> This is some warning.
```

I realized I could get 90% there by transforming those into blockquotes. That's not enough, though. I would need to attach that metadata (tip, warning) there to style these appropriately.

Here's what I came up with:

```javascript
'use strict';
var markdown = require('commonmark');

var mdReader = new markdown.Parser();
var mdWriter = new markdown.HtmlRenderer();

main();

function main() {
    var content = '# demo\nT> some tip\n\nW> some warning\n'
    var content2 = '> some';
    var parsed = mdReader.parse(content);

    parsed = transform(parsed);

    var result = mdWriter.render(parsed);

    console.log(result);
}

function transform(parsed) {
    var walker = parsed.walker();
    var event, node;

    while ((event = walker.next())) {
      node = event.node;
      if (event.entering && node.type === 'Text') {
        if(node.literal.indexOf('T>') === 0) {
            node._parent._classes = ['tip']; // XXX: not possible yet
            node._parent._type = 'BlockQuote';
            node.literal = node.literal.slice(2).trim();
        }
        if(node.literal.indexOf('W>') === 0) {
            // ... same thing for warning
        }
      }
    }

    return parsed;
}
```

Do you think it would be alright to add support for something like `._classes`? This would make it so much easier to do custom stuff like this. No doubt there are some other applications.

**Comment by iamstarkov** [comment]
I used to think that it is already possible with commonmark, i’m sad that it’s not. Yes we need this!

By _this_ I mean we need getter and setter to manipulate AST node classes. With this feaure we will conquer the world!

**Comment by jgm** [comment]
What do you mean by "node classes"?

**Comment by bebraw** [comment]
> What do you mean by "node classes"?

Ie. the above code would yield something like `<blockquote class="tip">` given `node._parent._classes` is set. I think you'll want to provide something more generic to keep the API sane, though. If it was possible to attach custom attributes to each HTML element, you could get these type of customizations done easily. Ie. `node.__attributes = {name: value}`. Or getter/setter like @iamstarkov proposed.

**Comment by iamstarkov** [comment]
I mean HTML classes in output for DOM nodes

**Comment by iamstarkov** [comment]
any news here?

**Comment by iamstarkov** [comment]
(sigh) it’s kinda disappointing

**Comment by iamstarkov** [comment]
right now, I need another feature. I want process markdown and add "id" to headings. @jgm what do you think about this?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Jun 24 15 12:31 ]:
>   right now, I need another feature. I want process markdown and add "id"
>   to headings. [1]@jgm what do you think about this?

It's fairly simple to modify the HTML renderer so it adds
automatic IDs to headings.  Feel free to do this in your own
branch; it's not going to be part of the reference
implementation, but the spec doesn't prohibit this kind
of variation in renderers.

**Comment by iamstarkov** [comment]
> Feel free to do this in your own branch; it's not going to be part of the reference implementation

why? this information can be used not only for HTML, but for other formats too, for example pdf.

**Comment by iamstarkov** [comment]
I just released [commonmark-helpers 0.4](http://npmjs.org/package/commonmark-helpers) with support for processing nodes. So right now we can do simple stuff like uppercasing literals. It is good base for a lot of plugins, but its not enough for extra stuff, e.g. adding ids to the headings. And I’m pretty sure that processing AST-tree is reference implementation’s responsibility and not renderer’s one. So basically I want to do like this:

```js
import { html, text, isHeader, matchProcess } from 'commonmark-helpers';
import unidecode from 'unidecode';

const addIDs = (node) => {
  if (isHeader(node)) {
    node.id = unidecode(text(node).replace(/\s/gim, '-').toLowerCase());
  }
};

html(matchProcess(`# AVE commonmark\n\npls add this feature`, addIDs));

/*
  <h1 id="ave-commonmark">AVE commonmark</h1>\n
  <p>pls add this feature</p>\n
*/
```

**Comment by iamstarkov** [comment]
it’s pretty simple and powerfull pattern for adding new commonmark extensions. The only thing required from reference implementation is to be more flexible and to let developers to set custom properties (like `id` or `className`) and then renderers will handle custom properties how they want it to handle. 

For example HTML renderer will handle `id`, `className` and other html attributes in normal html way.

**Comment by iamstarkov** [comment]
From my perspective as participator and active consumer this flexibillity is "must have" feature for commonmark.

**Comment by chrisalley** [comment]
> why? this information can be used not only for HTML, but for other formats too, for example pdf.

There's a [lengthy discussion](http://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115) about this over on the forum.

**Comment by iamstarkov** [comment]
my proposal not only about ids for headers. With more flexible spec it will be able to check if first symbols are `T>` or `W>` and then change current node type from 'Paragraph' to 'Blockquote' and add classes like `tip` for `T>` and probably `wisdom` for `W>`. More flexible spec ⇒ more posibillities to extensions

**Comment by chrisalley** [comment]
Proposals for the spec are discussed in the Spec forum category: http://talk.commonmark.org/c/spec

**Comment by iamstarkov** [comment]
Thanks, created topic with this proposal http://talk.commonmark.org/t/flexibility-and-modularity-for-the-win-and-also-extensions-ecosystem/1245

**Comment by jgm** [comment]
@iamstarkov - as others have noted, there are extensive discussions of possible extensions (including this) at http://talk.commonmark.org.  Please contribute there.  The priority now is to get the core spec finalized, and there's still plenty to do there.  After that we can think more about extensions.

I'm closing this, because it's premature to consider such additions to the reference parser.  Perfectly fine to discuss ideas on the forum.

Note that many things can be done by establishing conventions within standard CommonMark syntax.  For example, instead of

    W> This is a warning

you could do

    > ## WARNING
    > This is a warning

Then after parsing, you can use the "walker" (iterator) interface to walk the tree and convert block quotes that start with a header "WARNING" to anything you like (e.g. enclosing them in specially marked div tags, adding an image, etc.).

You could use a similar approach to add IDs to headers.  The advantage of this approach is that it degrades gracefully in normal Markdown parsers; you aren't relying on any non-standard parsing.

**Comment by iamstarkov** [comment]
> @iamstarkov - as others have noted, there are extensive discussions of possible extensions (including this) at http://talk.commonmark.org. Please contribute there. The priority now is to get the core spec finalized, and there's still plenty to do there. After that we can think more about extensions.
>
> I'm closing this, because it's premature to consider such additions to the reference parser. Perfectly fine to discuss ideas on the forum.

I already [created topic on talk.commonmark.org](http://talk.commonmark.org/t/flexibility-and-modularity-for-the-win-and-also-extensions-ecosystem/1245). Please contribute there =)

**Comment by iamstarkov** [comment]
> Then after parsing, you can use the "walker" (iterator) interface to walk the tree and convert block quotes that start with a header "WARNING" to anything you like (e.g. enclosing them in specially marked div tags, adding an image, etc.).
> 
> You could use a similar approach to add IDs to headers. The advantage of this approach is that it degrades gracefully in normal Markdown parsers; you aren't relying on any non-standard parsing.

I got your point about backward compatibillity, thanks. And didn’t get how can modify AST nodes with what you suggesting. Can you post and code sample?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Jun 29 15 03:33 ]:
>     Then after parsing, you can use the "walker" (iterator) interface to
>     walk the tree and convert block quotes that start with a header
>     "WARNING" to anything you like (e.g. enclosing them in specially
>     marked div tags, adding an image, etc.).
>
>     You could use a similar approach to add IDs to headers. The
>     advantage of this approach is that it degrades gracefully in normal
>     Markdown parsers; you aren't relying on any non-standard parsing.
>
>   I got your point about backward compatibillity, thanks. And didn’t get
>   how can modify AST nodes with what you suggesting. Can you post and
>   code sample?

There are a couple examples of using the walker interface in
the README.

For the header application, you could do something like
this:  on an enter header event, look at the header's
contents (available at node.firstChild and continuing on
using next.)  Look for a pattern you've designated.
(A nice, backwards compatible approach would be to use
an HTML coment to hold the identifier, since this would
just disappear in other renderers.)  If you find e.g.
`<!-- myident -->`, then set a property on the header
node, and remove the comment.

There are many ways you could do something like this -- I've
just given one example.

**Comment by iamstarkov** [comment]
sorry for bothering but I still didnt get how it will reflected in html and html-renderer

**Comment by jgm** [comment]
Of course, you'd have to modify the renderer too, to print the id
attribute.

**Comment by iamstarkov** [comment]
btw, AST ref spec is already flexible https://github.com/iamstarkov/commonmark-helpers/pull/4/files

**Comment by iamstarkov** [comment]
> The parser returns a Node. The following public properties are defined (those marked "read-only" have only a getter, not a setter):

these lines are confusing, but I forgot that it is JS.

**Comment by iamstarkov** [comment]
yay, it’s awesome

**Comment by iamstarkov** [comment]
> Of course, you'd have to modify the renderer too, to print the id attribute.

Are these changes are welcome in the commonmark’s html-render? i’m not talking about any messy stuff, but only about applying ids and classes from ast tree. is it okay?

**Comment by jgm** [comment]
+++ Vladimir Starkov [Jun 29 15 12:02 ]:
>     Of course, you'd have to modify the renderer too, to print the id
>     attribute.
>
>   Are these changes are welcome in the commonmark’s html-render? i’m not
>   talking about any messy stuff, but only about applying ids and classes
>   from ast tree. is it okay?

Not in the default renderer; we limit ourselves there to
recognized AST elements (corresponding to the ones that are
also found in cmark).

**Comment by iamstarkov** [comment]
probably it’s time to create its own html renderer

**Comment by iamstarkov** [comment]
> Not in the default renderer; we limit ourselves there to recognized AST elements

btw, wait. I dont want to create new AST element, I just want HTML renderer to consume custom id properties, like `id` and `class`. it is custom props not elements

**Comment by iamstarkov** [comment]
they [id and class] are not even custom for HTML
