### ISSUE TITLE
Named HTML entities with multiple codepoints not parsed correctly

### ISSUE THREAD

**Issue by robinst** [jgm/commonmark.js#47]
See the following example: http://spec.commonmark.org/dingus/?text=%26ngE%3B%0A%0A%26gE%3B

`&ngE;` should be rendered as "≧̸" (U+02267 U+00338), but it's actually rendered as "≧" (which is the same as `&gE;`)

It looks like other such named entities are also not handled correctly.

Would probably also be good to add such an entity to the spec so that implementations are checked for this.

**Comment by jgm** [comment]
I see that in cmark, `src/html_unescape.gperf`, the same
sequence is given for `ngE` and `gE`.

In commonmark.js, `lib/html5-entities.js`, `gE` is 8807 and
`ngE` is the same.

In commonmark.js, there is the further problem that the
entity decoding code seems to assume that each entity will
map on to a single code point.

I agree that a case like this should be in the spec, too.


+++ Robin Stocker [Jun 13 15 01:11 ]:

**Comment by jgm** [comment]
OK, everything should be fixed now!  Thanks for pointing out the problem.

**Comment by robinst** [comment]
Thanks for the quick reaction! :)
