### ISSUE TITLE
AST confusion

### ISSUE THREAD

**Issue by slang800** [jgm/commonmark.js#48]
Given the following script:

```coffee
{Parser} = require 'commonmark'

text = """
# test

some text

- list item one
- list item two
- list item three

more text
"""

parser = new Parser()
walker = parser.parse(text).walker()
console.log('''
hasNext | hasPrev | type | literal
------- | ------- | ---- | -------
''')
while event = walker.next()
  node = event.node
  console.log(
    [
      node.next isnt null
      node.prev isnt null
      node.type
      node.literal
    ].join(' | ')
  )
```

I get the following output:

hasNext | hasPrev | type | literal
------- | ------- | ---- | -------
false | false | Document | 
true | false | Header | 
false | false | Text | test
true | false | Header | 
true | true | Paragraph | 
false | false | Text | some text
true | true | Paragraph | 
true | true | List | 
true | false | Item | 
false | false | Paragraph | 
false | false | Text | list item one
false | false | Paragraph | 
true | false | Item | 
true | true | Item | 
false | false | Paragraph | 
false | false | Text | list item two
false | false | Paragraph | 
true | true | Item | 
false | true | Item | 
false | false | Paragraph | 
false | false | Text | list item three
false | false | Paragraph | 
false | true | Item | 
true | true | List | 
false | true | Paragraph | 
false | false | Text | more text
false | true | Paragraph | 
false | false | Document | 

Which has a couple problems:
- Child-nodes are returned without using the walker in each node (which makes the next/prev values really confusing)
- Container nodes are repeated (like `Header`-`Text`-`Header` and `Paragraph`-`Text`-`Paragraph` sets). This would make sense if the AST was flat and didn't show child / parent nodes (meaning that the duplicate nodes represent start/end HTML tags), However, there's no indication of which tags are start / end tags, and the AST isn't flat.

**Comment by jgm** [comment]
+++ Sean Lang [Jun 13 15 21:03 ]:
>   Which has a couple problems:
>     * Child-nodes are returned without using the walker in each node
>       (which makes the next/prev values really confusing)

I didn't understand what you meant by this.

>     * Container nodes are repeated (like Header-Text-Header and
>       Paragraph-Text-Paragraph sets). This would make sense if the AST
>       was flat and didn't show child / parent nodes (meaning that the
>       duplicate nodes represent start/end HTML tags), However, there's no
>       indication of which tags are start / end tags, and the AST isn't
>       flat.

Each container node is visited twice, once when entering,
and once when leaving.  You are only looking at `event.node`;
you should also look at `event.entering` to see whether you
are entering or leaving.  (That is your indication of
start/end.)

Note that you can interact with the AST directly.  The
walker interface just gives you an iterator interface for
interacting with it.  This is very handy for things like
writing renderers that don't use recursion, and it gives
you an easy way to traverse the whole tree doing queries
or transformations. But you don't have to use it.  You can
just directly use methods on nodes like `type`,
`firstChild`, `next`, `isContainer`, `appendChild`,
`insertAfter`, etc.

**Comment by slang800** [comment]
Ohh, now I get it - "writing renderers that don't use recursion" really explains the idea behind it. I thought I was supposed to treat this like a syntax tree and use the `node.firstChild()` / `node.next()` methods to iterate over the children of a given node.

Is there a good way to use this with a recursive renderer? Perhaps getting a representation of the AST as just a tree of objects like the following example?

```json
{
  "type": "Document",
  "children": [
    {
      "type": "Header",
      "children": [
        {"type": "Text", "literal": "test"}
      ]
    },
    {
      "type": "Paragraph",
      "children": [
        {"type": "Text", "literal": "some text"}
      ]
    },
    {
      "type": "List",
      "children": [
        {
          "type": "Item",
          "children": [
            {
              "type": "Paragraph",
              "children": [
                {"type": "Text", "literal": "list item one"}
              ]
            }
          ]
        },
        {
          "type": "Item",
          "children": [
            {
              "type": "Paragraph",
              "children": [
                {"type": "Text", "literal": "list item two"}
              ]
            }
          ]
        },
        {
          "type": "Item",
          "children": [
            {
              "type": "Paragraph",
              "children": [
                {"type": "Text", "literal": "list item three"}
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "Paragraph",
      "children": [
        {"type": "Text", "literal": "more text"}
      ]
    }
  ]
}
```

...or is the internal representation not structured like that?

PS: closing since this isn't an issue.

**Comment by jgm** [comment]
For technical reasons, the internal representation is structured as a linked list -- it does not use javascript arrays.

But if you want an AST with children in arrays, you can use the walker interface to construct it.

Something like:

``` js
Node.prototype.toObject = function() {
    var childrenStack = [];
    var walker = this.walker();
    var event;
    while ((event = walker.next())) {
        var node = event.node;
        var entering = event.entering;
        var container = node.isContainer();
        var astnode;

        if (container) {
            if (entering) {
                childrenStack.push([]);
            } else {
                astnode = nodeToObject(node);
                astnode.children = childrenStack.pop();
                if (childrenStack.length > 0) {
                    childrenStack[childrenStack.length - 1].push(astnode);
                }
            }
        } else {
            astnode = nodeToObject(node);
            childrenStack[childrenStack.length - 1].push(astnode);
        }
    }

    return astnode;

};
```

However, if you're writing a renderer, I'd recommend just using the iterator interface provided by walker.  Because it isn't recursive, you won't risk blowing the stack with highly nested constructions.  It's also really easy to write a renderer this way (see `lib/html.js` for an example).
