### ISSUE TITLE
Any plans for a Grunt plugin?

### ISSUE THREAD

**Issue by smohadjer** [jgm/commonmark.js#5]

**Comment by jgm** [comment]
Please elaborate.

**Comment by smohadjer** [comment]
I use a npm/grunt build process where one of the tasks is to convert markdown files into HTML during build. I have found one such plugin (see link below), but was wondering if there is one for commonmark.js in the pipeline.

https://www.npmjs.com/package/grunt-markdown

**Comment by jgm** [comment]
I hadn't planned to write one, as I don't use grunt.  But someone else
may want to write one!

+++ Saeid Mohadjer [Feb 15 15 10:04 ]:
