### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#52]
Does commonmark following semver? There is no features added in two last minor versions

**Comment by jgm** [comment]
Not yet.  We are keeping commonmark.js and cmark in sync with the
CommonMark spec versions, until we reach 1.0.  So, any time we have a bump
in the CommonMark spec version, we bump versions for the implementations
accordingly.  This will change when the spec hits 1.0.

**Comment by iamstarkov** [comment]
thanks for response

**Comment by colinodell** [comment]
Technically speaking it does follow SemVer:

> 4\. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/

**Comment by iamstarkov** [comment]
well… it’s only technical

**Comment by iamstarkov** [comment]
btw, what’s about roadmap #53?
