### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by iamstarkov** [jgm/commonmark.js#53]
cannot find any roadmap for commonmark. can anybody point me?

**Comment by thomasingalls** [comment]
talk.commonmark.org has a response from jgm about this: http://talk.commonmark.org/t/roadmap-for-commonmark/1081 ... in general, it looks like "solidify the core implementation, then consider extensions and other items."  No timeline estimates, as far as I have seen.

quoting jgm, in the above link, from March 2
> I'm not sure I can say anything very helpful here. There are still a few tricky things to resolve in core: chiefly raw HTML and backtick fences. I'd also like to get clearer about URL handling and normalization, and whether to use XML for the spec tests.

> My best guess is that we might get to thinking seriously about extensions this summer. (Summer is also when I have the most time to work on projects like this.)

**Comment by jgm** [comment]
I'm planning to post something on the forum with a list of open issues soon.
