### ISSUE TITLE
class injection in code block renderer

### ISSUE THREAD

**Issue by rlidwka** [jgm/commonmark.js#54]
Did you know that CommonMark supports buttons? Apparently it [does](http://spec.commonmark.org/dingus/?text=%60%60%60%26%23x0D%3Bbtn%26%23x0D%3Bbtn-primary%0AClick%20me!%0A%60%60%60):

![](https://cloud.githubusercontent.com/assets/999113/8465075/bba32066-204f-11e5-9539-8ebcca9ff5e6.png)

The trouble is: renderer appends the character class blindly to the `language-` part. If there are spaces there, we'll end up with `<code class="language-foo bar">` which is two separate classes.

Well technically space (0x20) is filtered. But HTML5 allows 5 space characters according to [2.4 part of the spec](http://www.w3.org/TR/html5/infrastructure.html#space-character). I'll quote:

> The **space characters**, for the purposes of this specification, are U+0020 SPACE, "tab" (U+0009), "LF" (U+000A), "FF" (U+000C), and "CR" (U+000D).

So, this code block will have three classes: `language-foo`, `bar` and `baz`:

    ```foo&#x09;bar&#x0C;baz
    code
    ```

Second and third are essentially user-supplied, which is usually a bad thing.

**Comment by jgm** [comment]
Good catch!
