### ISSUE TITLE
"Smart" replacement of hyphens with em/en dash seems strange

### ISSUE THREAD

**Issue by bfrohs** [jgm/commonmark.js#56]
The current tests in `smart_punct.txt` for en/em dashes don't define behavior for certain longer combinations and the current code ends up resulting with hanging hyphens when they could be easily replaced in a different manner to only replace them with em/en dashes.

For example, a series of 10 hyphens results in 3 em dashes followed by a hyphen. In my opinion, it would make more sense for this to result in 5 en dashes. Additionally, 7 hyphens are converted into 2 em dashes and a hyphen, but I believe it should be 1 em dash and 2 en dashes. That is:

```
Current: ---------- => --- --- --- -  => ———-
 Better: ---------- => -- -- -- -- -- => –––––

Current: ------- => --- --- - => ——-
 Better: ------- => --- -- -- => —––
```

To achieve this behavior, each group of hyphens would be collected and counted at once, assuming it is 2 hyphens or more (eg, `/^(?<!-)(-{2,})/`), and then the most optimal grouping would be figured out (in PHP for `thephpleague/commonmark`, but should be able to be converted to JavaScript/C fairly easily):

```php
$count = strlen($matched);
$en_dash = '–';
$en_count = 0;
$em_dash = '—';
$em_count = 0;
if ($count % 3 === 0) { // If divisible by 3, use all em dashes
    $em_count = $count / 3;
} elseif ($count % 2 === 0) { // If divisible by 2, use all en dashes
    $en_count = $count / 2;
} elseif (($count - 2) % 3 === 0) { // If 2 extra dashes, use en dash for last 2; em dashes for rest
    $em_count = floor(($count - 2) / 3);
    $en_count = 1;
} else { // Use en dashes for last 4 hyphens; em dashes for rest
    $em_count = floor(($count - 4) / 3);
    $en_count = 2;
}
$inlineContext->getInlines()->add(new Text(
    str_repeat($em_dash, $em_count).
    str_repeat($en_dash, $en_count)
));
return true;
```

Is this something that CommonMark would be interested in implementing? (I can do, I just don't want to spend the time writing the code if it won't be accepted.) Or should the smart_punct.txt file be updated with tests that check for these edge cases?

**Comment by jgm** [comment]
Interesting idea.  It departs from the simplicity of the
current system, and I think simplicity is good for users.
(You don't have to think too hard to figure out what it
will do.)  On the other hand, you're likely right that
if someone did write a long string of dashes, they wouldn't
intend it to be a combination of em or en dashes and a
hyphen.  Another solution, of course, would be to treat
any sequence longer than 3 hyphens as just a literal
sequence of hyphens.

**Comment by colinodell** [comment]
+1 I think it would be useful to define the ideal behavior for these longer sequences.

**Comment by bfrohs** [comment]
> Another solution, of course, would be to treat any sequence longer than 3 hyphens as just a literal sequence of hyphens.

I don't think leaving the literal hyphens is a good idea, since there are times when [consecutive em dashes are needed for editorial](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0002.html):

> ...in a bibliographic list, rather than repeating the same author over and over again, three consecutive em dashes (also known as a 3-em dash) stand in for the author’s name.



> In interrupted speech, one or two em dashes may be used: “I wasn’t trying to imply——”

So, that leaves the current behavior or the proposed behavior as viable options.

> On the other hand, you're likely right that if someone did write a long string of dashes, they wouldn't intend it to be a combination of em or en dashes and a hyphen.

As far as I can tell, there's no need (at least in English) for an em dash or en dash to be followed by another dash or the hyphen. There also doesn't seem to be a need for consecutive en dashes.

So, it really comes down to what the user expects `----` to become: "– –" or "— -" (space added to help visualize).

In any case, having the behavior defined in the spec is preferred.

**Comment by jgm** [comment]
On reflection, I like the proposal.

Agree about the spec, too.  At this point the closest we have to a spec for this is [`test/smart_punct.txt` in jgm/cmark](
https://github.com/jgm/cmark/blob/master/test/smart_punct.txt).  We'd need to modify the spec and test runner to make it possible to include tests for options.

**Comment by bfrohs** [comment]
> Agree about the spec, too. At this point the closest we have to a spec for this is test/smart_punct.txt in jgm/cmark. We'd need to modify the spec and test runner to make it possible to include tests for options.

Are you talking about the `{smart: true}` option? We'd really only need a couple tests, specifically strings of 7  and 10 hyphens, to test for this behavior. Would need the options feature for testing edge cases down the road that pop up, but I think adding a couple tests to `test/smart_punct.txt` would be good enough for now. Would you like me to go ahead and make these changes?

**Comment by jgm** [comment]
+++ Brandon Frohs [Jul 09 15 13:21 ]:
>     Agree about the spec, too. At this point the closest we have to a
>     spec for this is test/smart_punct.txt in jgm/cmark. We'd need to
>     modify the spec and test runner to make it possible to include tests
>     for options.
>
>   Are you talking about the {smart: true} option? We'd really only need a
>   couple tests, specifically strings of 7 and 10 hyphens, to test for
>   this behavior. Would need the options feature for testing edge cases
>   down the road that pop up, but I think adding a couple tests to
>   test/smart_punct.txt would be good enough for now. Would you like me to
>   go ahead and make these changes?

Sure, go ahead and submit a PR.
