### ISSUE TITLE
tab-related regressions

### ISSUE THREAD

**Issue by rlidwka** [jgm/commonmark.js#59]
I didn't quite understand 0.21 spec changes related to tabs. The general idea seems good, but devil is in the details as they say. So I checked this implementation, unfortunately, it's behavior appears to be buggy.

Tab immediately after list item marker was allowed, now it's not. Is it intentional?

```sh
$ echo -e ' -\tlist' | ./commonmark-0.20
<ul>
<li>list</li>
</ul>

$ echo -e ' -\tlist' | ./commonmark-0.21 
<p>-	list</p>
```

If code block indentation is using half a tab, what happens?

```sh
$ echo -e ' - foo\n\n\t\tbar' | ./commonmark-0.20
<ul>
<li>
<p>foo</p>
<pre><code> bar
</code></pre>
</li>
</ul>

$ echo -e ' - foo\n\n\t\tbar' | ./commonmark-0.21
<ul>
<li>
<p>foo</p>
<p>ar</p>
</li>
</ul>
```

Variation of the bug above. But it might deserve a special place because it's unclear whether ` - \t\tcode` should be a code block or not (might be a bug in 0.20 actually):

```sh
$ echo -e ' - \t\tcode' | ./commonmark-0.20
<ul>
<li>code</li>
</ul>

$ echo -e ' - \t\tcode' | ./commonmark-0.21 
<ul>
<li>
<pre><code>de
</code></pre>
</li>
</ul>
```

**Comment by jgm** [comment]
Yes, these are all bugs.

Note that cmark behaves correctly in each case.  Since the code is fairly similar, it shouldn't be too hard to fix these.

**Comment by jgm** [comment]
Actually, there's an interesting question about this case:
```
echo -e ' - foo\n\n\t\tbar' | cmark
echo -e ' - foo\n\n        bar' | cmark
```
One might think from the spec that these would be equivalent.  However, they're not; in the second case, but not the first ,we get a space at the start of the code block.  Actually, that strikes me as reasonable behavior -- after all, there's no space character in the code block.  But I don't think the spec ties this down tightly enough.

**Comment by jgm** [comment]
We should add test cases to the spec with tabs after list markers, block quote markers, and elsewhere.

**Comment by jgm** [comment]
Note to self:  I'm not convinced cmark is quite right either, looking at the code.

**Comment by jgm** [comment]
Note that 94053a8928b7ee600abc56d3f481e98b0dc438a3 fixes the missing characters problems in the original cases above, but we still have the problem that we're getting a regular paragraph rather than a code block.

```
% echo -e ' - foo\n\n\t\tbar' | bin/commonmark 
<ul>
<li>
<p>foo</p>
<p>bar</p>
</li>
</ul>
```
