### ISSUE TITLE
Blockquote termination edge-case

### ISSUE THREAD

**Issue by rlidwka** [jgm/commonmark.js#60]
The spec says, “An indented code block cannot interrupt a paragraph.”

So this looks right:

```sh
$ echo -e '> 111\n    222' | ./commonmark-0.20 
<blockquote>
<p>111
222</p>
</blockquote>
```

But a list can:

```sh
$ echo -e '> 111\n - 222' | ./commonmark-0.20 
<blockquote>
<p>111</p>
</blockquote>
<ul>
<li>222</li>
</ul>
```

The trouble comes when the thing after the blockquote looks like this:

```md
> 111
    - 222
```

```sh
$ echo -e '> 111\n    - 222' | ./commonmark-0.20 
<blockquote>
<p>111</p>
</blockquote>
<pre><code>- 222
</code></pre>
```

It terminates a blockquote saying “hey, I'm a list”, but is parsed as a code block afterwards.

Imho, it should be parsed like a paragraph continuation after all:

```html
<blockquote>
<p>111
- 222</p>
</blockquote>
```

**Comment by jgm** [comment]
This is a commonmark.js bug.  Note that, again, cmark parses this correctly.
Probably worth adding an example like this in the spec.
