### ISSUE TITLE
Parser adds lines to a tip which can't accept them

### ISSUE THREAD

**Issue by colinodell** [jgm/commonmark.js#67]
Here's an example which exhibits this behavior:

~~~markdown
10. Bullet

        code


Test
~~~

The issue occurs when parsing line 5.  As you can see, it checks whether the container (a `CodeBlock`) accepts lines, but then adds the line to the tip instead (which is a `Document`):

![selection_167](https://cloud.githubusercontent.com/assets/202034/10046006/671559c6-61d4-11e5-84ae-bf53468fc4ac.png)

![selection_168](https://cloud.githubusercontent.com/assets/202034/10046008/6980f10c-61d4-11e5-8e3c-dda3d14479b4.png)

According to the comments on lines 117-118, the tip should be checked to see if it handles lines.  Would it therefore be true that line 723 should check the tip type instead of the container type?  Or is there perhaps an issue with the tip being out-of-sync with the container?

**Comment by jgm** [comment]
Something does look wrong here:  in line 5 (the second blank line), the CodeBlock should still be open (and it should be the tip).

To clarify, though: do you get an error or incorrect output when running commonmark.js on this input?  I don't.

I can't actually remember why I used "tip" for addLine.  In the C code, addLine just takes an explicit node as argument.

**Comment by colinodell** [comment]
> To clarify, though: do you get an error or incorrect output when running commonmark.js on this input? I don't.

I don't either, but my PHP port of this project does (because we throw an exception if `addLine` is called on something which doesn't accept lines).

> I can't actually remember why I used "tip" for addLine. In the C code, addLine just takes an explicit node as argument.

When I looked at the C code I didn't see any mention of a "tip".  Would it make sense to eliminate the tip altogether by replacing all instances with the container instead?

**Comment by colinodell** [comment]
Thank!
