### ISSUE TITLE
Italics inside Bold text can parse as double em instead of strong

### ISSUE THREAD

**Issue by moemoe760** [jgm/commonmark.js#68]
When trying to parse:
`1. **one t*w*o three** `
you are returned:
```html
<ol>
<li><em><em>one t</em>w</em>o three**</li>
</ol>
```
You would expect:
```html
<ol>
<li><strong>one t<em>w</em>o three</strong></li>
</ol>
```
It's taking the first to asterisks as opening EMs and the other 2 around the "w" as closing

Live exmaple: http://spec.commonmark.org/dingus/?text=1.%20**one%20t*w*o%20three**

note: it also has the same effect if you put the string in without the list: `**one t*w*o three** `
Live example: http://spec.commonmark.org/dingus/?text=**one%20t*w*o%20three**

**Comment by jgm** [comment]
The way this is parsed is consistent with [the declarative rules in the spec](http://spec.commonmark.org/0.22/#emphasis-and-strong-emphasis) and the algorithm described at the end of the spec.  I agree that this parsing is not the one a human might naturally expect, but unless we build humanlike AI into the algorithm, I think such cases are probably going to be inevitable.

I'm open to suggestions for changes in the rules and parsing algorithm that would parse this sample as you expect without messing other things up.

**Comment by moemoe760** [comment]
I've been digging into this and i think the change lies inside the left_flanking & right flanking concept.
Correct me if i'm wrong but you don't get a tag unless you have both an opening and a closing tag:
`**bold**` works and `**bold` is just plain text.
Using that idea, wouldn't the way to parse it to be to run a recursive parse on the inline tags:
something along the lines of:
```
recursiveParse(textBlock){
    while (walk through the string){
        if (start of block is identified){
            find end of block (first matching closing tag, e.g. double asterisk)
            recrusiveParse(textBlock.substring(start of text block, position of closing tag))
        }
    }
    parse current block and add to AST
}
```
of course the actual implementation would have to be taught out but this pseudo code gets at the general idea.
That way you can have anything inside anything and it will work.
(I haven't tested all possible scenarios and stuff it's just a general idea)

**Comment by jgm** [comment]
There are many complexities here.  One is that you can't
know, when you see something like `**` or `***`, whether
this is the beginning of a strong or an emph span (or
neither).  So, what is the "first matching closing tag"?

The current parsing algorithm (described at the
end of the spec) answers questions like this in a principled
way.  It is the fruit of a lot of experience and thought.
It also avoids the kind of exponential performance problems
you can easily get with recursive algorithms that allow
backtracking.  Maybe it can be improved, but please study
the existing algorithm before proposing another.


+++ moemoe760 [Sep 29 15 12:47 ]:
