### ISSUE TITLE
HTTPS download link

### ISSUE THREAD

**Issue by btrask** [jgm/commonmark.js#71]
The readme has a link to the compiled source here: http://spec.commonmark.org/js/commonmark.js

I think we should try to be encouraging developers to get their code over HTTPS, to prevent problems like the recent Xcode attack.

Simply changing the above link to https didn't work (cert domain error). It seems to be hosted on GitHub but I couldn't figure out the correct invocation through GitHub pages or whatever. This URL does work though: https://raw.githubusercontent.com/jgm/CommonMark-site/gh-pages/js/commonmark.js

Thanks.

Edit: this would also apply to the whole CommonMark site, but one step at a time...

**Comment by jgm** [comment]
This will also work:

https://raw.githubusercontent.com/jgm/commonmark.js/master/dist/commonmark.js

or for versioned,

https://raw.githubusercontent.com/jgm/commonmark.js/0.22.0/dist/commonmark.js

I'll update the README.

+++ Ben Trask [Nov 03 15 08:31 ]:

**Comment by btrask** [comment]
Thanks!
