### ISSUE TITLE
No way to set list attributes on a commonmark.Node

### ISSUE THREAD

**Issue by nicojs** [jgm/commonmark.js#74]
When using the abstract syntax tree directly there is no way to set the list attributes (listType, listDelimiter, listStart and listTight) without initializing the _listData yourself. As it starts with an underscore i think this seems to be a private property and should not be interacted with directly.

For example:
```javascript
var node = new commonmark.Node('List');
node.listType = 'bullet'; // TypeError: Cannot set property 'delimiter' of null
```

**Comment by jgm** [comment]
See in lib/node.js:
```
Object.defineProperty(proto, 'listType', {
    get: function() { return this._listData.type; },
    set: function(t) { this._listData.type = t; }
});
```
and so on for the others.  This sets a public getter and setter for the property (as documented in README).  The problem is that in this case, where you create a List node the way you do, `_listData` isn't yet defined.

I think the fix is to modify node.js as follows:
```
Object.defineProperty(proto, 'listType', {
    get: function() { return this._listData && this._listData.type; },
    set: function(t) { this._listData = this._listData || {}; this._listData.type = t; }
});
```

**Comment by jgm** [comment]
Actually a better idea is to initialize `_listData` to `{}` when a node is created.

**Comment by nicojs** [comment]
Thank you!
Op 14 dec. 2015 07:12 schreef "John MacFarlane" <notifications@github.com>:
