### ISSUE TITLE
Usage instructions for the command line executable

### ISSUE THREAD

**Issue by DanielBaird** [jgm/commonmark.js#80]
The command line `commonmark` isn't mentioned in the readme, and doesn't respond to `--help`, `-h`, `-?`, or any of the other usual requests for usage info.

I deduced that it expects a CM stream and produces a HTML output stream, so I'll pull-req a paragraph into the Readme mentioning it, but ideally there'd be a line or two of usage behind `--help` or `-h`.

**Comment by jgm** [comment]
Closed by #81.
