### ISSUE TITLE
Bug: two blank line break out of all the lists which should not

### ISSUE THREAD

**Issue by lotabout** [jgm/commonmark.js#89]
I've put this into [a discussion](http://talk.commonmark.org/t/possible-bug-of-list-and-blockquote/2025).

Consider the following markdown text:
```
1. > 1. a
   > 
   > 
   > 1. b  <- should be a child of the blockquote
```
The element `b` should be a child of the blockquote

Currently, commonmark.js will give [this result](http://spec.commonmark.org/dingus/?text=1.%20%3E%201.%20a%0A%20%20%20%3E%20%0A%20%20%20%3E%20%0A%20%20%20%3E%201.%20b%20%20%3C-%20should%20be%20a%20child%20of%20the%20block), while the expected one is [like this](https://markdown-it.github.io/#md3={%22source%22%3A%221.%20%3E%201.%20a\n%20%20%20%3E%20\n%20%20%20%3E%20\n%20%20%20%3E%201.%20b%20%20%3C-%20should%20be%20a%20child%20of%20the%20block%22%2C%22defaults%22%3A{%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22}})

**Comment by jgm** [comment]
This is now irrelevant since we've gotten rid of "two blank lines break out of a list."
