### ISSUE TITLE
Question on markerOffset

### ISSUE THREAD

**Issue by tmpfs** [jgm/commonmark.js#94]
I am close to getting the basics of nested lists working in my markdown renderer however it appears possibly that `markerOffset` cannot always be used to determine leading whitespace indentation.

For an input of:

```markdown
1. fruits
  * apples
  * oranges
  * pears
2. vegetables
  - potatoes
  - beans
    - french
    - long
```
I get `markerOffset` zero for the ordered list and 2 for the initial nested lists (both values appear to me to be correct given my understanding of the code), however for the deep nested list I get `markerOffset` zero again - I would expect it to be 4. Am i missing something? Can I use `markerOffset` to correctly indent nested lists?

**Comment by tmpfs** [comment]
I am using this to quickly check values:

```
cat test/fixtures/nested-list.md | commonmark --ast | grep markerOffset
```

Test fixture is here:

https://github.com/mkdoc/mkout/blob/master/test/fixtures/nested-list.md

**Comment by jgm** [comment]
`markerOffset` is the offset, not including any necessary indentation to get you inside a containing block element.  Notice that in your example, the unordered list items are not indented far enough to be a sublist of the ordered list item "1.".  That's why you get an offset.  "- french" and "- fries" by contrast are indented far enough to be a sublist -- indeed, *just* far enough, hence the offset is 0.  Hope that makes sense now.

**Comment by tmpfs** [comment]
Ok, I think I understand (partly), so `markerOffset` should not be used to determine leading indentation for lists.

Although I am not clear on:

> the unordered list items are not indented far enough to be a sublist of the ordered list item "1.

I am using two spaces indentation which I thought was enough. I have re-read the spec on lists and it appears that two spaces is enough from [example 277](http://spec.commonmark.org/0.24/#example-277).

What am I missing?

**Comment by tmpfs** [comment]
Playing with the dingus things are becoming clearer :)

So to create a sublist within an ordered list 3 spaces are required, but it appears that for unordered lists 2 is enough - is that correct?

**Comment by jgm** [comment]
+++ muji [Mar 21 16 00:32 ]:
>   Playing with the dingus things are becoming clearer :)
>
>   So to create a sublist within an ordered list 3 spaces are required,
>   but it appears that for unordered lists 2 is enough - is that correct?

No.  Everything is explained in the spec, section 5.2.
"The most important thing to notice is that the position of
the text after the list marker determines how much
indentation is needed in subsequent blocks in the list item.
If the list marker takes up two spaces, and there are three
spaces between the list marker and the next non-whitespace
character, then blocks must be indented five spaces in order
to fall under the list item."

**Comment by tmpfs** [comment]
Sorry, I clearly wasn't paying enough attention.

Thank you - that is very helpful!
