### ISSUE TITLE
Maybe bug in blocks.js RegExp

### ISSUE THREAD

**Issue by NikolaDasm** [jgm/commonmark.js#98]
Missing backslash (\s) in
new RegExp('^(?:' + OPENTAG + '|' + CLOSETAG + **')\s*$'**, 'i').

**Comment by jgm** [comment]
Where do you think a backslash is missing?  The source
does contain `\s`.

+++ NikolaDasm [Apr 23 16 05:55 ]:

**Comment by NikolaDasm** [comment]
In file lib/blocks.js, line 27.

**Comment by jgm** [comment]
Here is the line:

```
    new RegExp('^(?:' + OPENTAG + '|' + CLOSETAG + ')\s*$', 'i')
```
There's already a backslash before the s.  So, why do you say one is missing there?

**Comment by NikolaDasm** [comment]
Look at this example:
re1 = new RegExp('^a\s*$');
re2 = new RegExp('^a\\s*$');
console.log(re1.test('a     '));
console.log(re2.test('a     '));
console.log(re1.test('asssss'));

**Comment by jgm** [comment]
Thanks, sorry I was being dense about this.
